carro/urls.py
from . import views
from django.urls import path
app_name="carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name="agregar"),
    path('agregar_home/<int:producto_id>/', views.agregar_home, name="agregar_home"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="eliminar"), 
    path('restar/<int:producto_id>/', views.restar_producto, name="restar"), 
    path('limpiar/', views.limpiar_carro, name="limpiar"), 
    path('limpiar_producto/', views.limpiar_carro_producto, name="limpiar_producto"), 
]

core/urls.py
from collections import namedtuple
from django.urls import path
from django.urls.conf import include
from .views import *    
from django.contrib import admin

urlpatterns = [
    #Home
    path('',home, name='home'), 
    #contacto
    path('contacto/', contacto, name="contacto"),
    #producto
    path('agregarproducto/', agregar_producto, name="agregar_producto"),
    path('listarproducto/', listar_productos, name="listar_producto"),
    path('modificarproducto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminarproducto/<id>/', eliminar_producto, name="eliminar_producto"),
    #registro
    path('register/', register, name="register"),
    #familia
    path('listar_familias/', listar_familias, name='listar_familias' ),
    path('nueva_familia/', nueva_familia, name='nueva_familia'),
    path('modificarfamilia/<id>/', modificar_familia, name="modificar_familia"),
    path('eliminarfamilia/<id>/', eliminar_familia, name="eliminar_familia"),
    #Factura
    path('listar_factura/', listar_factura,name='listar_factura'),
    path('nueva_factura/', nueva_factura, name='nueva_factura'),
    path('modificarfactura/<id>/', modificar_factura,name='modificar_factura'),
    path('eliminarfactura/<id>/',eliminar_factura,name='eliminar_factura'),
    #Boleta
    path('listar_boleta/', listar_boleta,name='listar_boleta'),
    path('nueva_boleta/', nueva_boleta, name='nueva_boleta'),
    path('modificarboleta/<id>/', modificar_boleta,name='modificar_boleta'),
    path('eliminarboleta/<id>/',eliminar_boleta,name='eliminar_boleta'),
    #Proveedor
    path('listar_proveedor/', listar_proveedor, name='listar_proveedor' ),
    path('nuevo_proveedor/', nuevo_proveedor, name='nuevo_proveedor'),
    path('modificarproveedor/<id>/', modificar_proveedor, name="modificar_proveedor"),
    path('eliminarproveedor/<id>/', eliminar_proveedor, name="eliminar_proveedor"),
    #TBK
    path('tbkRes/', statusTrx, name="tbkRes"),
    #Carrito
    path('cart/', cart, name="cart"),
    #usuario
    path('usuario/<id>/', usuario , name='usuario'),
    path('nuevo_usuario/', nuevo_usuario, name='nuevo_usuario'),
    path('listar_usuario/',listar_usuario , name='listar_usuario'),
    path('modificar_usuario/<id>/',modificar_usuario,name='modificar_usuario'),
    path('eliminarusuario/<id>/',eliminar_usuario, name='eliminar_usuario'),
    #Modulos
    path('empleado/',empleado, name='empleado'),
    path('administrador/',administrador, name='administrador'),
    path('proveedor/',provedor, name='provedor'),
    #OrdenCompra
    path('listar_orden/', listar_orden, name='listar_orden' ),
    path('nueva_orden/', nueva_orden, name='nueva_orden'),
    path('modificarorden/<id>/', modificar_orden, name="modificar_orden"),
    path('eliminarorden/<id>/', eliminar_orden, name="eliminar_orden"),
]

musicpro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/',include('usuario.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('carro/', include('carro.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from typing import ClassVar
from django import forms
from django.contrib import auth
from django.db import models
from django.db.models import fields
from django.forms import widgets    
from .models import *
from django.contrib.auth.models import User
from django.forms.widgets import Select
class ContactoForms(forms.ModelForm):
    
    class Meta:
        model = contacto
        #Fiedls detalla todos los datos para el formulario como se necesitan todos se usa __all__
        fields = '__all__'

#widget para fecha de vencimiento de producto


class AgregarProductoForms(forms.ModelForm):
    class Meta:
        model = producto
        fields = '__all__'
        widgets = {
        "vencimiento": forms.SelectDateWidget() 
        }

class AgregarFamiliaForms(forms.ModelForm):
    class Meta:
        model = familia
        fields = '__all__'






class AgregarProveedorForms(forms.ModelForm):
    class Meta:
        model = proveedor
        fields = '__all__'


class AgregarOrdenForms(forms.ModelForm):
    
    class Meta:
        model = ordencompra
        fields = '__all__'
class ModificarOrdenForms(forms.ModelForm):

    class Meta:
        model = ordencompra
        fields = ('proveedor','documento','estado')
        widgets = {
            'proveedor':Select(attrs={
                'class':'form-control select2',
                'style':'width: 100%',
                'type':'disabled'

            }),
            'documento':Select(attrs={
                'class':'form-control select2',
                'style':'width: 100%',
                'type':'disabled'
            }),
            'estado': Select(attrs={
                'class':'form-control select2',
                'style':'width: 100%',
            })
        }

core/views.py
from factura.models import factura
from usuario.models import Usuario
from django.forms.forms import Form
import carro
from django.contrib.messages.api import success
from django.core import paginator
from django.http import request
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from .models import  *
from .forms import *
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth import authenticate,login
from django.db import connection
import cx_Oracle
from django.views.decorators.csrf import csrf_exempt
from .services import *
from carro.context_processor import *
import json
from usuario.forms import FormularioUsuario, FormularioUsuarioCompleto,AgregadoAdminForms
from factura.forms import FacturaForm
from boleta.forms import BoletaForm
from boleta.models import boleta
# Create your views here.
#Home de la pagina
def home(request):
    productos = producto.objects.all() 
    data = {
        'producto': productos,
    }
    return render(request, 'core/home.html', data)
#formulario de contacto
def contacto(request):
    data = {
        'form': ContactoForms()
    }
    if request.method == 'POST':
        formulario = ContactoForms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "contacto guardado"
        else:
            data["form"] = formulario
    return render(request, 'core/Contacto.html',data)
#Productos
#Procedimiento para agregar producto
def agregar_producto(request):

    data = {
        'form': AgregarProductoForms()  
    }
    if request.method == 'POST':
        formulario = AgregarProductoForms(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto registrado correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: El producto no fue registrado")

    return render(request, 'core/producto/agregar.html', data)
#Funcion listar prodcutos
def listar_productos(request):
    data = {
        'familias':listar_familia(),
        'producto':lista_prodcuto(),
    }
    return render(request, 'core/producto/listar.html',data)
#Procedimiento listar productos
def lista_prodcuto():
    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    out_cur = django_cursor.connection.cursor()
    cursor.callproc('core_productos_listar', [out_cur])
    lista = []
    for fila in out_cur:
        lista.append(fila)
    return lista
#Procedimiento para modificar producto
def modificar_producto(request, id):
    product = get_object_or_404(producto, id=id)
    data = {
        'form': AgregarProductoForms(instance=product)
    }
    if request.method == 'POST':
        formulario = AgregarProductoForms(data=request.POST,instance=product, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Producto modificado correctamente ")
            return redirect(to="listar_producto")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: No se pudo modificar el producto")
    return render(request, 'core/producto/modificar.html', data)
#Procedimiento para eliminar producto
def eliminar_producto(request, id ):
    prod = get_object_or_404(producto, id=id)
    prod.delete()
    messages,success(request, "Producto eliminado correctamente")
    return redirect(to="listar_producto")
#Registro de clientes
def register(request):
    data = {
        'form':FormularioUsuario()
    }
    if request.method == 'POST':
        formulario = FormularioUsuario(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"],password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Registro exitoso")
            return redirect(to="home")
        data['from'] = formulario
    return render(request, 'registration/register.html', data)

#Familias
#Funcion listar familias
def listar_familias(request):
    data = {
        'familia':listar_familia()
    }
    return render(request, 'core/familia/listar.html', data)
#funcion de almacenado de familias
def nueva_familia(request):
    data = {
        'form': AgregarFamiliaForms()  
    }
    if request.method == 'POST':
        formulario = AgregarFamiliaForms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Familia registrada correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: La Familia no fue registrada")

    return render(request, 'core/familia/agregar.html', data)
#Procedimiento para llamar a las familias
def listar_familia():
    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    out_cur = django_cursor.connection.cursor()
    cursor.callproc('core_familia_listar', [out_cur])
    lista = []
    for fila in out_cur:
        lista.append(fila)
    return lista
#Procedimiento para guardar familias
def agregar_familia(nombre):
    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    salida = cursor.var(cx_Oracle.NUMBER)
    cursor.callproc('core_familia_agregar',[nombre,salida])
    return salida.getvalue()
#Procedimiento para eliminar familia    
def eliminar_familia(request, id ):
    fam = get_object_or_404(familia, id=id)
    fam.delete()
    messages,success(request, "Familia eliminada correctamente")
    return redirect(to="listar_familias")
#Procedimiento para modificar familia
def modificar_familia(request, id):
    famil = get_object_or_404(familia, id=id)
    data = {
        'form': AgregarFamiliaForms(instance=famil)
    }
    if request.method == 'POST':
        formulario = AgregarFamiliaForms(data=request.POST,instance=famil)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Familia modificada correctamente ")
            return redirect(to="listar_familias")
        else:
            data["form"] = formulario
            
    return render(request, 'core/familia/modificar.html', data)


#Proveedores 
#Funcion de listado de proveedores
def listar_proveedor (request):
    data = {
        'proveedor':listar_proveedores()
    }
    return render(request,'core/proveedor/listar.html',data)
#Funcion de almacenado de proveedor
def nuevo_proveedor(request):
    data = {
        'form': AgregarProveedorForms()  
    }
    if request.method == 'POST':
        formulario = AgregarProveedorForms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Proveedor registrado correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: El proveedor no fue registrado")

    return render(request, 'core/proveedor/agregar.html', data)
#Procedimiento de listado de proveedores
def listar_proveedores():
    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    out_cur = django_cursor.connection.cursor()
    cursor.callproc('core_proveedor_listar', [out_cur])
    lista = []
    for fila in out_cur:
        lista.append(fila)
    return lista
#Procedimiento para guardar proveedores
def agregar_proveedor(rut,nombre,telefono,rubro):
    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    salida = cursor.var(cx_Oracle.NUMBER)
    cursor.callproc('core_proveedor_agregar',[rut,nombre,telefono,rubro,salida])
    return salida.getvalue()
#Procedimiento para eliminar proveedor
def eliminar_proveedor(request, id ):
    prov = get_object_or_404(proveedor, id=id)
    prov.delete()
    messages,success(request, "Proveedor eliminado correctamente")
    return redirect(to="listar_proveedor")
#Procedimiento modificar Proveedor 
def modificar_proveedor(request, id):
    prov = get_object_or_404(proveedor, id=id)
    data = {
        'form': AgregarProveedorForms(instance=prov)
    }
    if request.method == 'POST':
        formulario = AgregarProveedorForms(data=request.POST,instance=prov)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Proveedor modificado correctamente ")
            return redirect(to="listar_proveedor")
        else:
            data["form"] = formulario
            
    return render(request, 'core/proveedor/modificar.html', data)

#TBK
@csrf_exempt
def statusTrx(request):
    data = {
        'resultado': get_statusTBK(request),
    }
    return render(request, 'core/tbk/statusTbk.html',data)
#Carrito
@csrf_exempt
def cart(request):
    product = producto.objects.all()
    monto = request.POST.get('precio_total')
    data = {
        'producto': product,
        'resultado': get_initTrxTBK(monto),
    }
    return render(request, 'core/carro/cart.html', data)    

#Factura
def nueva_factura(request):
    data = {
        'form':FacturaForm(),
    }
    if request.method == 'POST':
        formulario = FacturaForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, " Factura Registrada correctamente ")
        else:
            data["form"] = formulario
            messages.warning(request, "ERROR: la factura no fue registrada")
    return render(request, 'core/factura/agregar.html',data)

def listar_factura(request):
    factur = factura.objects.all()
    data = {
        'factura':factur
    }
    return render(request, 'core/factura/listar.html',data)

def modificar_factura(request,id):
    fact = get_object_or_404(factura, id=id)
    data = {
        'form': FacturaForm(instance=fact)
    }

core/templates/core/Contacto.html
{% extends 'core/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}

<div class="col-12 col-md-6 offset-md-3 ">
    <div class=" row p-3 mb-2 ">
            <div class="card">
                <div class="card-body">
                    <h2>Contacto</h2>
            
            
                    <form action="" method="POST">
            
                        {% csrf_token %}
                        {{ form | crispy }}
                        <br>
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" id="btnCancelar" class="btn btn-secondary">
                            &nbsp;
                            <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                    
                        </div>
                    
                    </form>
                    {{mensaje}}
            
                </div>
            </div>
        </div>
</div>



{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MusicPRO</title>
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
   <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
   <script type="text/javascript">
		var user = '{{request.user}}'

		function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getToken('csrftoken')
	
	</script>
  {% block css %}
  {% endblock %}

  {% block head %}
  {% endblock %}
</head>

<body id="intro" class="bg-image shadow-2-strong">
  <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/img/LOGITO2.png' %}" height="60" alt="logo"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Inicio</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Categorias
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for f in familia %}
            <a class="dropdown-item" href="#">{{ f.1 }}</a>
            {% endfor %}
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacto' %}">Contáctanos</a>
        </li>
        {% if user.cargo.id == 3 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'empleado' %}">Área Empleados</a>
        </li>
        {% endif %}
        {% if user.cargo.id == 4 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'provedor' %}">Área Proveedores</a>
        </li>
        {% endif %}
        {% if user.cargo.id == 2 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'administrador' %}">Área Administración</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'usuario' user.id %}">Usuario: {{ user.cargo |title }}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Iniciar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
        </li>
        {% endif %}
        <li class="nav-item">
          
        </li>
      </ul>
      <a class="nav-link d-flex align-items-center" href="{% url 'cart' %}">
        <img id="cart-icon" style="width:20px;" src="{% static 'images/cart.png' %}" alt="carrito" />
        <p id="cart-total" class="float-right">{{importe_cant_carro}}</p>
      </a>

    </div>
  </nav>

  <div class="contenedorprincipal d-flex">
  {% block contenido %}

  {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

  {% if messages %}
      {% for m in messages %}
        <script>
          Swal.fire(

              "Excelente",
              "{{m}}",
              "success"
          )


        </script>
      {% endfor %}
    {% endif %}
  {% block js %}
 

  {% endblock %}
  <footer class="text-center text-lg-start">
    <div class="container d-flex justify-content-center py-5">
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2">
        <i class="fab fa-facebook-f"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2">
        <i class="fab fa-youtube"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2">
        <i class="fab fa-instagram"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2">
        <i class="fab fa-twitter"></i>
      </button>
    </div>

<!-- Copyright -->
    <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2021
      <a class="text-white" href="{% url 'home' %}">MusicPRO</a>
    </div>
<!-- Copyright -->
</footer>
</body>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}
{% block contenido %}
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="1" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'css/herramientas.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Respuesta oportuna</h5>
            <p>Entender sus requerimientos
              Aprender de sus experiencias</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'css/herramientass.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Cotizamos tus requerimientos</h5>
            <p>Cotizaciones completas y en tiempo pactado</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'css/herramientasss.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Entrega On Time</h5>
            <p>Recibe tu pedido en tiempo y lugar pactado</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Anterior</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Siguiente</span>
    </a>
  </div>

  <hr>
    <h2 class="text-center">PRODUCTOS RECOMENDADOS</h2>
    <hr>
    <div class="container">
      <div class="row text-center">
        {% for p in producto %}
          {% if p.oferta == 1 %}
          <div class="col-md-4 pb-1 pb-md-0">
            <div class="card" style="background-color: #DADADA;">
              {% if p.imagen %}
              <div>
                <img src="{{ p.imagen.url }}" class="card-img-top" alt="imagen">
              </div>
              {% else %}
              <div>
                <img src="{% static '/images/default.jpg' %}" class="card-img-top" alt="imagen">
              </div>
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{ p.nombre }}</h5>
                <p class="card-text">{{ p.descripcion }}</p>
                <p class="card-text">${{ p.precio | intcomma}}</p>
                <a href="{% url 'carro:agregar_home' p.id %}" class="btn btn-primary">Añadir al carrito</a>
              </div>
            </div>        
          </div>
          {% endif %}
        {% endfor %}
      </div>
    </div>
    
    
{% endblock %}

core/templates/core/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if producto.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ producto.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != producto.number and paginator.num_pages > 7 %} 
                {% if producto.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ producto.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == producto.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == producto.number %}
            <li class="page-item {% if page == producto.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if producto.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ producto.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if producto.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ producto.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if producto.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ producto.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}